### ISSUE TITLE
package pytenet

### ISSUE THREAD

**Issue by jcmgray** [cmendl/pytenet#1]
Looks like there is lot's of cool stuff here! Regarding https://github.com/openjournals/joss-reviews/issues/948:

It would be good if ``pytenet`` was structured as a standard install-able python package. Specifically, it needs a ``setup.py`` file with requirements etc. specified along with an ``__init__.py`` file in the main module subdirectory. Plenty of resources on this but there's a [very bare-bones example here](https://github.com/kennethreitz/samplemod).

**Comment by cmendl** [comment]
Ok, thanks, I'll add that.

BTW I find the quimb toolbox very nice and elegant! (Admittedly didn't know about it before..)

**Comment by jcmgray** [comment]
Nice, thanks. 

> BTW I find the quimb toolbox very nice and elegant! (Admittedly didn't know about it before..)

Yeah it's hard to search through all these projects and I have not really been publicizing it! Of course if you see any opportunities for cross-pollination between the projects that would be cool - there are lots of features in ``pytenet`` that ``quimb`` does not yet implement.

**Comment by cmendl** [comment]
resolved by commit 416dc73a1b6eae276d0139a82354aec6b0077406
